# Generated by Django 5.0.3 on 2024-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdescription', models.TextField()),
                ('joblocation', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=50)),
                ('jobfunction', models.CharField(max_length=50)),
                ('jobeducation', models.CharField(max_length=100)),
                ('joblevel', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdescription', models.TextField()),
                ('joblocation', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=50)),
                ('jobfunction', models.CharField(max_length=50)),
                ('jobeducation', models.CharField(max_length=100)),
            ],
        ),
    ]
