# Generated by Django 5.0.6 on 2024-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobpay_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='jobpay_min',
            field=models.IntegerField(default=0),
        ),
    ]
