# Generated by Django 5.0.6 on 2024-07-19 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_job_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Contract', 'Contract'), ('Part-time', 'Part-time'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
