# Generated by Django 5.0.6 on 2024-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_job_posted_date_alter_job_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobpay_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobpay_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
    ]
