# Generated by Django 5.0.6 on 2024-07-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_job_jobpay_max_remove_job_jobpay_min_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
