# Generated by Django 5.0.6 on 2024-07-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdescription', models.TextField()),
                ('joblocation', models.CharField(max_length=100)),
                ('jobtype', models.CharField(choices=[('Full time', 'Full time'), ('Contract', 'Contract'), ('Part-time', 'Part-time'), ('Remote', 'Remote')], max_length=50)),
                ('jobfunction', models.CharField(max_length=50)),
                ('jobeducation', models.CharField(max_length=100)),
                ('joblevel', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('jobpay_min', models.PositiveIntegerField(default=0)),
                ('jobpay_max', models.PositiveIntegerField(default=0)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
